#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

# Settings are automatically loaded as bash variables
# in every app script context, therefore typically these will exist:
# - $domain
# - $path
# - $language
# - $install_dir
# - $port
# ...

# For remove operations :
# - the core will deprovision every resource defined in the manifest **after** this script is ran
# this includes removing the install directory, and data directory (if --purge was used)

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
# REMOVE SYSTEMD SERVICE 
#=================================================
ynh_script_progression --message="Removing system configurations related to $app..." --weight=1

# This should be a symetric version of what happens in the install script

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_exec_warn_less yunohost service status $app >/dev/null
then
	ynh_script_progression --message="Removing $app service integration..." --weight=1
	yunohost service remove $app
fi

ynh_remove_systemd_config

ynh_remove_nginx_config

ynh_remove_logrotate

# Remove other various files specific to the app... such as :

ynh_secure_remove --file="/var/log/$app"

# Restore LDAP configuration
# conf_regen hook will be deleted by YunoHost AFTER this remove script execution
# So I detele it and regenerate conf files
# NOTA: I try to generate only LDAP conf with "sudo yunohost tools regen-conf sladp" but, in this
# case, the hooks are not called. Not a problem for this app but could be a problem if there are
# hooks from others apps.
ynh_script_progression --message="Restore LDAP configuration..." --weight=2
sudo bash -c "rm /etc/yunohost/hooks.d/conf_regen/*portainer"
yunohost tools regen-conf

# Firewall should NOT allow Docker containers internal IP to reach MySQL
# Should be the OPPOSITE as ../hooks/post_iptable_rules
iptables -D INPUT -s 192.168.0.0/16 -p tcp -m tcp --dport 389 -j ACCEPT
iptables -D INPUT -s 172.16.0.0/12 -p tcp -m tcp --dport 389 -j ACCEPT

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Removal of $app completed" --last
